# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-datadog-integration
  description: Terraform module to configure Datadog AWS integration
  homepage: https://cloudposse.com/accelerate
  topics: terratest, datadog, terraform-modules, hcl2, aws

