name: "auto-update"
on:
  schedule:
    # Update context.tf and README.md nightly
    - cron:  '0 0 * * *'

jobs:
  context-update:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update context.tf
        shell: bash
        id: update
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          if [[ -f context.tf ]]; then
            echo "context.tf exist! Fetching most recent version to see if there is an update"
            curl -o context.tf -s https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
            if git diff --no-patch --exit-code context.tf; then
              echo "No changes detected! Exiting the job..."
              echo "MAKE_PR=false" >> $GITHUB_ENV
              exit 0
            else
              echo "context.tf file was updated. Proceeding with PR..."
              echo "MAKE_PR=true" >> $GITHUB_ENV
              exit 0
            fi
          else
            echo "context.tf does not exist! It is not enough to fetch context.tf, module requires to be updated to support it."
            echo "MAKE_PR=false" >> $GITHUB_ENV
            exit 0
          fi

      - name: Create Pull Request
        if: ${{ success() && env.MAKE_PR == 'true' }}
        uses: cloudposse/actions/github/create-pull-request@0.20.0
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          commit-message: Update context.tf from origin source
          title: Update context.tf
          body: |-
            ## what
            This is an auto-generated PR that updates the context.tf file

            ## why
            To have most recent changes of `context`

          branch: auto-update/context.tf
          base: master
          delete-branch: true
          labels: |
            auto-update
            context

  readme-update:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update readme
        shell: bash
        id: update
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          make init
          make readme/build

      - name: Create Pull Request
        uses: cloudposse/actions/github/create-pull-request@0.20.0
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          commit-message: Update README.md and docs
          title: Update README.md and docs
          body: |-
            ## what
            This is an auto-generated PR that updates the README.md and docs

            ## why
            To have most recent changes of README.md and doc from origin templates

          branch: auto-update/readme
          base: master
          delete-branch: true
          labels: |
            auto-update
            readme
